name: assembly-readme

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'site/resources/*.adoc'

env:
  # PHP Configuration
  PHP_MODULES: none,bcmath,bz2,calendar,Core,ctype,curl,date,dom,exif,fileinfo,filter,gd,hash,iconv,intl,json,libxml,mbstring,openssl,pcre,PDO,Phar,readline,Reflection,session,SimpleXML,soap,sockets,SPL,standard,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib
  PHPUNIT_DIR: ${{ github.workspace }}/target/analysis/phpunit
  PHPUNIT_LOG: ${{ github.workspace }}/target/analysis/phpunit/phpunit-test.log

  # User Configuration
  AUTH_DIR: "${HOME}"

  DOCU_SRC_DIR: "site/resources"

jobs:
  assembly-readme:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        version: [ 24 ]
        php: ["8.4"]
    runs-on: ${{ matrix.os }}
    permissions:
        contents: write
        actions: write

    steps:
      - name: set current timestamp
        id: TS_NOW
        run: echo "TS_NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: echo current timestamp
        run: echo ${TS_NOW} - ${{ env.TS_NOW }} - ${{ steps.TS_NOW.outputs.TS_NOW }}

      - name: create target dir
        run: mkdir -p ${{ env.PHPUNIT_DIR }}

      - name: checkout
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer

      - name: assembly README.adoc
        run: asciidoctor-reducer --preserve-conditionals -o README.adoc ${{ env.DOCU_SRC_DIR }}/pj-readme.adoc

      - name: assembly config.adoc
        run: asciidoctor-reducer --preserve-conditionals -o docu-config.adoc ${{ env.DOCU_SRC_DIR }}/pj-config.adoc

      - name: assembly analysis.adoc
        run: asciidoctor-reducer --preserve-conditionals -o docu-analysis.adoc ${{ env.DOCU_SRC_DIR }}/pj-analysis.adoc

      - name: assembly commmands.adoc
        run: asciidoctor-reducer --preserve-conditionals -o docu-commands.adoc ${{ env.DOCU_SRC_DIR }}/pj-commands.adoc

      - name: assembly examples.adoc
        run: asciidoctor-reducer --preserve-conditionals -o docu-examples.adoc ${{ env.DOCU_SRC_DIR }}/pj-examples.adoc

      - name: assembly usage.adoc
        run: asciidoctor-reducer --preserve-conditionals -o docu-usage.adoc ${{ env.DOCU_SRC_DIR }}/pj-usage.adoc

      - name: commit and push documents
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: |
            - README.adoc
            - docu-config.adoc
            - docu-analysis.adoc
            - docu-commands.adoc
            - docu-examples.adoc
            - docu-usage.adoc
